title: Elizeu 'Ligeirinho'
description: Site sobre Projetos, Plano de Governo e propostas de Elizeu De Souza para o município de Primeiro De Maio
author: Elizeu De Souza
theme: jekyll-theme-architect
